dotenv: .env

# default ganache network
networks:
    default: ftm-main-fork

# automatically fetch contract sources from Ftmscan
autofetch_sources: True

dependencies:
    - yearn/yearn-vaults@0.4.3-1
    - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support imports from GitHub
compiler:
    solc:
        version:
        remappings:
            - "@yearnvaults=yearn/yearn-vaults@0.4.3-1"
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
